feat: UI of DashBoard page
ezzio/project_management_horenso pull request #112
Opened 2022-01-02 04:26 UTC by nguyendang127

![image](https://user-images.githubusercontent.com/72656184/147866193-7440da24-b1cd-42b1-b1c5-ae631759199b.png)

2022-01-02 05:36 UTC, pum-k requested changes
Thanh timeline của grantt chart chuyển theo đơn vị tháng được không? (vd: 01/2021), nếu kiểu này thì nó sẽ khá là dài:
![image](https://user-images.githubusercontent.com/75214138/147867254-c239f0d3-3dba-4b9c-b692-05c755b55cfc.png)

Ngoài ra Task Chart vs Kanban Chart đang quá rộng, giảm width đi 20%.
Trưởng hợp Task, Kanban, Project không có dữ liệu (chưa có) thì cần hiện `No Data`

2022-01-02 06:31 UTC, nguyendang127 commented
width của Task Chart và Kanban Chart nếu giảm lại sẽ bị trống phía bên phải khiến cho Timeline Chart phải bung rộng ra để lắp vào chỗ trống đó. Gantt Chart thì tui chưa nắm được có thể thay đổi ngày hay không nhưng trước mắt là không thể thay đổi. 
Trường hợp TimeLine, Task và Kanban không có dữ liệu thì hiện thị ``No Data`` sẽ cập nhật lại

2022-01-03 06:56 UTC, nguyendang127 commented
Theo như đã nói ở trên thì thanh ngày tháng không thể thay đổi. Mong anh Khoa thông cảm, phần width tôi đã chỉnh sửa như ý và khi không có dữ liệu cả 3 chart đã hiện ``No Data`` "bên dưới là hình minh họa"
- Khi có dữ liệu
![image](https://user-images.githubusercontent.com/72656184/147905669-a8656ec0-d77b-4cfe-a1ed-97fc6a23c490.png)

- Khi không có dữ liệu
![image](https://user-images.githubusercontent.com/72656184/147905702-f60cf47d-4785-4b25-9dcc-2678b4f53a21.png)

2022-01-03 07:46 UTC, pum-k commented
![image](https://user-images.githubusercontent.com/75214138/147908542-b9eee9bf-6261-4723-af5c-11fee4b7ee51.png)
Tăng witdh của timeline lên.
**Thanh timeline của grant chart phải tìm cách chuyển sang dạng tháng `!important`**

2022-01-05 05:31 UTC, nguyendang127 commented
![image](https://user-images.githubusercontent.com/72656184/148165320-712797a9-7f4f-4864-95b4-c2c2a126007d.png)
- Thêm process chart
- Điều chỉnh UI 
- Điều chỉnh timeline của Gantt Chart sang tháng

2022-01-05 05:42 UTC, nguyendang127 commented
- Vừa sửa content của process chart từ "Task" sang "Process"

2022-01-05 05:49 UTC, pum-k commented
> ![image](https://user-images.githubusercontent.com/72656184/148165320-712797a9-7f4f-4864-95b4-c2c2a126007d.png)
> - Thêm process chart
> - Điều chỉnh UI 
> - Điều chỉnh timeline của Gantt Chart sang tháng

Làm tốt lắm. Nhưng có vài misunderstand ở đây:
1. Kanban chart đổi tên thành Job chart.
2. Xóa process chart vì nó chính là kanban chart hiện tại.
Nhìn chung khá ổn rồi. Chăm chút css 1 tí và thử gắn sider vào xem có responsive chưa.

2022-01-05 05:51 UTC, pum-k commented
> > ![image](https://user-images.githubusercontent.com/72656184/148165320-712797a9-7f4f-4864-95b4-c2c2a126007d.png)
> > - Thêm process chart
> > - Điều chỉnh UI 
> > - Điều chỉnh timeline của Gantt Chart sang tháng
> 
> Làm tốt lắm. Nhưng có vài misunderstand ở đây:
> 1. Kanban chart đổi tên thành Job chart.
> 2. Xóa process chart vì nó chính là kanban chart hiện tại.
> 
> 
> Nhìn chung khá ổn rồi. Chăm chút css 1 tí và thử gắn sider vào xem có responsive chưa.
> 
> 
Yêu cầu thêm: màu của chart nên phối theo bộ màu của dự án nằm ở color.scss

2022-01-06 10:20 UTC, lcnhut070200 commented
> > > ![image](https://user-images.githubusercontent.com/72656184/148165320-712797a9-7f4f-4864-95b4-c2c2a126007d.png)
> > > 
> > > * Thêm process chart
> > > * Điều chỉnh UI
> > > * Điều chỉnh timeline của Gantt Chart sang tháng
> > 
> > 
> > Làm tốt lắm. Nhưng có vài misunderstand ở đây:
> > 
> > 1. Kanban chart đổi tên thành Job chart.
> > 2. Xóa process chart vì nó chính là kanban chart hiện tại.
> > 
> > Nhìn chung khá ổn rồi. Chăm chút css 1 tí và thử gắn sider vào xem có responsive chưa.
> 
> Yêu cầu thêm: màu của chart nên phối theo bộ màu của dự án nằm ở color.scss

Màu dự án đang khá tối. Đề nghị refactor lại theme. Xin hết

2022-01-07 04:26 UTC, pum-k approved these changes

2022-01-08 04:53 UTC, nguyendang127 commented
![image](https://user-images.githubusercontent.com/72656184/148631991-80a10afc-ef38-4b68-8373-1e177ff85c08.png)

2022-01-09 07:49 UTC, pum-k commented
@ezzio pass

2022-01-09 08:05 UTC, merged