Refactor: Storage page
ezzio/project_management_horenso pull request #128
Opened 2022-01-13 09:00 UTC by lcnhut070200

- Update search debounce.
<img width="1552" alt="Screen Shot 2022-01-13 at 3 59 52 PM" src="https://user-images.githubusercontent.com/58385680/149298518-46f00244-461c-4e41-9103-6b48f6c5200f.png">

- Show file from detailsTask.
<img width="1552" alt="Screen Shot 2022-01-13 at 3 59 18 PM" src="https://user-images.githubusercontent.com/58385680/149298471-58fc333c-33b2-42b5-bf2d-8d412e857b77.png">

2022-01-14 01:50 UTC, pum-k requested changes
Good job! ✅

Nhưng trường hợp tôi là người dùng và tôi đã xem file đó xong, bây giờ tôi muốn list tất cả file lại, có thể cài một nút lệnh đc không, tôi không muốn search lại.

![feedback #128](https://user-images.githubusercontent.com/75214138/149437672-c2d32d52-6595-497e-adf7-f0ceaed070a4.gif)

2022-01-14 14:39 UTC, lcnhut070200 commented
- Đã update search input khi click chọn file từ trang detailTask.
- Có nút xóa nhanh input.
<img width="1552" alt="Screen Shot 2022-01-14 at 9 37 54 PM" src="https://user-images.githubusercontent.com/58385680/149533143-7fbbf0a8-9f9d-4d5a-b01e-164eba3a8533.png">

2022-01-15 01:40 UTC, pum-k commented
> * Đã update search input khi click chọn file từ trang detailTask.
> * Có nút xóa nhanh input.
> 
> <img alt="Screen Shot 2022-01-14 at 9 37 54 PM" width="1552" src="https://user-images.githubusercontent.com/58385680/149533143-7fbbf0a8-9f9d-4d5a-b01e-164eba3a8533.png">

nút clear hơi nhô và nên cho nó sát góc phải, bỏ icon iron man đi

2022-01-15 06:36 UTC, pum-k approved these changes

2022-01-15 06:36 UTC, merged