fix: refactor DashBoard page
ezzio/project_management_horenso pull request #151
Opened 2022-01-20 12:55 UTC by nguyendang127

2022-01-21 03:25 UTC, pum-k requested changes

2022-01-21 03:25 UTC, pum-k commented on client/src/pages/Dashboard/Dashboard.jsx
> +                      Job's Status
Job's Status = Task's Status

2022-01-21 04:06 UTC, pum-k commented
![image](https://user-images.githubusercontent.com/75214138/150463972-d2bbde6c-239b-4571-90cf-d0f433836ac1.png)

Please fix this animation when i change tab

2022-01-21 04:12 UTC, nguyendang127 commented
Roger that !!!

2022-01-22 00:49 UTC, nguyendang127 commented
I have sticked the Animate of Motion for you to check , sorry for this problems :(((

2022-01-22 02:53 UTC, pum-k approved these changes

2022-01-22 02:53 UTC, merged